################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Global Currency Solution
  productionDescription: Merchants or acquirers can unlock the power of FX with our suite of products. Our APIs enable real-time currency conversion at the point of sale for card present and card not present transactions. Cardholders receive transparent FX rates, merchants enhance the cardholder experience while settling in the currency of their choice, and acquirers provide their merchants with tools enhancing the cardholder experience. <br/><br/>Our suite of FX Solutions includes:<ul><li><a href="/product/GlobalCurrencySolutions/docs/?path=docs/dynamic-currency-conversion.md">Dynamic Currency Conversion (DCC)</a></li><li><a href="/product/GlobalCurrencySolutions/docs/?path=docs/multicurrency-pricing.md">Multi-Currency Pricing (MCP)</a></li></ul> To test with our APIs, review the GET STARTED page for more information. </br>
  whoIsItFor: Merchants, Financial Institutions
  image:
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Global Currency Solution
getStarted: /docs/getting-started.md
### not using Benefits section
#benefits:
#  - title:
#    description:
#  - title:
#    description:
#  - title:
#    description:

featuredFeatures:
  - title: FX Rate Provider
    description:  Market makers or treasuries can provide FX rates for Dynamic Currency Conversion transactions.
    tags: [ "Global Currency Solution", "FXExchange", "Currency Conversion" ]
    bullets: [ "Global Currency Solution", "Currency Conversion" ]
    relatedDocs:
      - relatedDoc:
        title: Getting Started
        description: Getting Started
        link: docs/getting-started.md
  - title: Issuing Currency Conversion
    description: Issuers can offer a currency conversion experience for their cardholders. Coming Soon.
    tags: [ "Global Currency Solution", "FXExchange", "Currency Conversion" ]
    bullets: [ "Global Currency Solution", "Currency Conversion" ]
  - title: MCP Enhanced
    description: Merchants are given transparency about the final settlement amount and cardholders can shop in their preferred currency. Coming Soon.
    tags: [ "Global Currency Solution", "FXExchange", "Currency Conversion" ]
    bullets: [ "Global Currency Solution", "Currency Conversion" ]

