################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Global Currency Solution
  productionDescription: Unlock the power of FX in your application with our robust API integration. Our developer-friendly API allows you to enable real-time currency conversion at the point of sale for card present and card not present transactions. By leveraging our API, you can offer users transparent exchange rates. <br/><br/>Our suite of FX Solutions includes:<ul><li>Dynamic Currency Conversion (DCC)</li><li>Multi-Currency Pricing (MCP)</li><li>Dynamic Pricing (DP)</li></ul><b>Major functional APIs are Exchange Rate and Boarding APIs. </b><ul><li><b>Exchange Rate APIs let you retrieve FX rates and BINs by making API </b>requests.</li><ul><li>The Get Rate API lets you retrieve the  FX rate based on the BIN and source currency (Use for DCC) </li><li>The Get All Rates API lets you retrieve a set of FX rates for a currency (Use for DP and MCP)   </li><li>The Get BINS by Currency API lets you retrieve the list of available BINs given a currency code (Use DP and MCP)</li></ul><li><b>Boarding APIs let you retrieve, create and update clients and locations by making API requests. </b></li><ul><li>The Create or Update Client API lets you create or update a Client ID (Use for DCC) </li><li>The Create or Update Location API lets you create or update a Location ID (Use for DCC) </li><li>The Get All Sub Client Locations API lets you retrieve the locations associated with a Client ID (Use for DCC)</li><li>The Get Client Location  API lets you retrieve the location detail for locations associated with a Client ID (Use for DCC) </li></ul>
  whoIsItFor: Merchants, Financial Institutions
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Global Currency Solution

featuredFeatures:
  - title: REPLACE ME
    description:  REPLACE ME
    tags: ["REPLACEME", "REPLACEME", "REPLACEME"]
    bullets: ["REPLACEME", "REPLACEME" ]  
    relatedDocs:
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME1.md
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME2.md
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME3.md
    relatedAPIs:
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "patch"        
        path: "/v1/REPLACEME1"
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "post"        
        path: "/v1/REPLACEME2"
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "get"        
        path: "/v1/REPLACEME3"
