################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Global Currency Solution
  productionDescription: Merchants or acquirers can unlock the power of FX with our suite of products. Our APIs enable real-time currency conversion at the point of sale for card present and card not present transactions. Cardholders receive transaparent FX rates, merchants enhance the cardholder experience while settling in the currency of their choice, and acquirers provide their merchants with tools enhancing the cardholder experience. <br/><br/><b>Our suite of FX Solutions includes:</b><ul><li>Dynamic Currency Conversion (DCC)</li><li>Multi-Currency Pricing (MCP)</li></ul><b>Major functional APIs for these products are Exchange Rate and Boarding APIs. </b><ul><li><b>Exchange Rate Retrieval</b><br/><br/><b>The Exchange Rate APIs</b> allow clients to obtain exchange rates based on specific parameters. These parameters may include the currency pair (source and target currency), client ID, location ID, and the BIN (Bank Identification Number).</li><li><b>Boarding </b><br/><br/>The <b>Client Management APIs</b> are used to create or update Client information. Customers can also retrieve a list of locations associated with a specific Client. The Client level sits above the Location level.<br/>The <b>Location Management APIs</b> are used to create or update Location information. Location represents the lowest level in the OpenFX hierarchy and is the individual merchant location. Customers can also retrieve information for a specific location based on its unique identifier. </li></ul>
  whoIsItFor: Merchants, Financial Institutions
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Global Currency Solution
getStarted: /docs/getting-started.md
benefits:
  - title: Increase revenue
    description: Help increase sales - up to 60% sales volume growth through expansion.
  - title: Minimize costs
    description: Earn revenue from processing foreign issued cards through a direct revenue share, or by including margin in pricing.
  - title: Better experience
    description: Lower shopping card abandonment - over 30% of shoppers will bail if their currency is not offered.

featuredFeatures:
  - title: FX Rate Provider
    description:  FX Rate Provider can be used for treasuries to provide FX rates for Dynamic Currency Conversion or Dynamic Pricing transactions.
    tags: [ "Global Currency Solution", "FXExchange", "Currency Conversion" ]
    bullets: [ "Global Currency Solution", "Currency Conversion" ]
    relatedDocs:
      - relatedDoc: 
        title: Getting Started
        description: Getting Started
        link: docs/getting-started.md
  - title: Alternative Payment Methods
    description: COMING SOON
    tags: [ "Global Currency Solution", "FXExchange", "Currency Conversion" ]
    bullets: [ "Global Currency Solution", "Currency Conversion" ]
  - title: ATM
    description: COMING SOON
    tags: [ "Global Currency Solution", "FXExchange", "Currency Conversion" ]
    bullets: [ "Global Currency Solution", "Currency Conversion" ]

